spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/camunda
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

camunda.bpm.admin-user:
  id: rakesh
  password: Xasyst@2023#

